// Twenty sample clients, drawn at random from the test extract and slightly
// perturbed. They live here so the page needs nothing but the API.
const FEATURES = [
  "anciennete_mois",
  "sieges_souscrits",
  "utilisateurs_actifs",
  "taux_adoption_pct",
  "connexions_30j",
  "heures_usage_30j",
  "fonctionnalites_utilisees",
  "nb_integrations",
  "derniere_connexion_jours",
  "tickets_support_90j",
  "delai_reponse_support_h",
  "csat",
  "retards_paiement_12m",
  "revenu_mensuel_recurrent_eur",
  "inactivite_relative",
  "inactif_30j",
  "taux_fonctionnalites",
  "polarite_csm_alerte",
  "polarite_csm_neutre",
  "polarite_csm_positif",
  "polarite_csm_absent",
  "niveau_anciennete_recent",
  "niveau_anciennete_etabli",
  "niveau_anciennete_ancien"
];

const CLIENTS = [
  {
    "client_id": "CLI-000100",
    "anciennete_mois": 1,
    "sieges_souscrits": 42,
    "utilisateurs_actifs": 9,
    "taux_adoption_pct": 17.59,
    "connexions_30j": 1,
    "heures_usage_30j": 0.1,
    "fonctionnalites_utilisees": 7,
    "nb_integrations": 0,
    "derniere_connexion_jours": 14,
    "tickets_support_90j": 5,
    "delai_reponse_support_h": 10.04,
    "csat": 2,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 927.8,
    "inactivite_relative": 0.48,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.47,
    "polarite_csm_alerte": 1,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-001528",
    "anciennete_mois": 1,
    "sieges_souscrits": 3,
    "utilisateurs_actifs": 1,
    "taux_adoption_pct": 32.47,
    "connexions_30j": 6,
    "heures_usage_30j": 1.6,
    "fonctionnalites_utilisees": 1,
    "nb_integrations": 0,
    "derniere_connexion_jours": 5,
    "tickets_support_90j": 4,
    "delai_reponse_support_h": 16.5,
    "csat": 4,
    "retards_paiement_12m": 2,
    "revenu_mensuel_recurrent_eur": 63.57,
    "inactivite_relative": 0.18,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.06,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 1,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-002807",
    "anciennete_mois": 17,
    "sieges_souscrits": 451,
    "utilisateurs_actifs": 264,
    "taux_adoption_pct": 54.37,
    "connexions_30j": 33,
    "heures_usage_30j": 7.17,
    "fonctionnalites_utilisees": 13,
    "nb_integrations": 2,
    "derniere_connexion_jours": 2,
    "tickets_support_90j": 6,
    "delai_reponse_support_h": 7.28,
    "csat": 3,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 24634.98,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.59,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 1
  },
  {
    "client_id": "CLI-004035",
    "anciennete_mois": 13,
    "sieges_souscrits": 1,
    "utilisateurs_actifs": 1,
    "taux_adoption_pct": 45.42,
    "connexions_30j": 75,
    "heures_usage_30j": 78.04,
    "fonctionnalites_utilisees": 4,
    "nb_integrations": 6,
    "derniere_connexion_jours": 0,
    "tickets_support_90j": 0,
    "delai_reponse_support_h": 11.17,
    "csat": 4,
    "retards_paiement_12m": 2,
    "revenu_mensuel_recurrent_eur": 12.17,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.51,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 1,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-002371",
    "anciennete_mois": 20,
    "sieges_souscrits": 31,
    "utilisateurs_actifs": 27,
    "taux_adoption_pct": 89.2,
    "connexions_30j": 48,
    "heures_usage_30j": 34.92,
    "fonctionnalites_utilisees": 7,
    "nb_integrations": 3,
    "derniere_connexion_jours": 5,
    "tickets_support_90j": 9,
    "delai_reponse_support_h": 20.79,
    "csat": 2,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 894.51,
    "inactivite_relative": 0.01,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.5,
    "polarite_csm_alerte": 1,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 1
  },
  {
    "client_id": "CLI-001825",
    "anciennete_mois": 15,
    "sieges_souscrits": 10,
    "utilisateurs_actifs": 8,
    "taux_adoption_pct": 87.07,
    "connexions_30j": 69,
    "heures_usage_30j": 8.64,
    "fonctionnalites_utilisees": 3,
    "nb_integrations": 5,
    "derniere_connexion_jours": 1,
    "tickets_support_90j": 1,
    "delai_reponse_support_h": 10.62,
    "csat": 4,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 143.93,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.37,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 1,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 1
  },
  {
    "client_id": "CLI-002468",
    "anciennete_mois": 7,
    "sieges_souscrits": 33,
    "utilisateurs_actifs": 12,
    "taux_adoption_pct": 33.63,
    "connexions_30j": 1,
    "heures_usage_30j": 0.09,
    "fonctionnalites_utilisees": 2,
    "nb_integrations": 2,
    "derniere_connexion_jours": 31,
    "tickets_support_90j": 0,
    "delai_reponse_support_h": 17.27,
    "csat": 4,
    "retards_paiement_12m": 1,
    "revenu_mensuel_recurrent_eur": 350.02,
    "inactivite_relative": 0.16,
    "inactif_30j": 1,
    "taux_fonctionnalites": 0.26,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 1,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 1,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-001423",
    "anciennete_mois": 21,
    "sieges_souscrits": 11,
    "utilisateurs_actifs": 7,
    "taux_adoption_pct": 56.79,
    "connexions_30j": 21,
    "heures_usage_30j": 8.0,
    "fonctionnalites_utilisees": 10,
    "nb_integrations": 6,
    "derniere_connexion_jours": 3,
    "tickets_support_90j": 8,
    "delai_reponse_support_h": 20.81,
    "csat": 2,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 254.75,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.51,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 1
  },
  {
    "client_id": "CLI-004142",
    "anciennete_mois": 15,
    "sieges_souscrits": 48,
    "utilisateurs_actifs": 33,
    "taux_adoption_pct": 64.51,
    "connexions_30j": 43,
    "heures_usage_30j": 22.73,
    "fonctionnalites_utilisees": 7,
    "nb_integrations": 2,
    "derniere_connexion_jours": 0,
    "tickets_support_90j": 0,
    "delai_reponse_support_h": 5.46,
    "csat": 5,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 2648.46,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.35,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 1
  },
  {
    "client_id": "CLI-002189",
    "anciennete_mois": 5,
    "sieges_souscrits": 170,
    "utilisateurs_actifs": 0,
    "taux_adoption_pct": 45.23,
    "connexions_30j": 0,
    "heures_usage_30j": 0.0,
    "fonctionnalites_utilisees": 0,
    "nb_integrations": 0,
    "derniere_connexion_jours": 43,
    "tickets_support_90j": 2,
    "delai_reponse_support_h": 16.61,
    "csat": 3,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 3933.94,
    "inactivite_relative": 0.33,
    "inactif_30j": 1,
    "taux_fonctionnalites": 0.0,
    "polarite_csm_alerte": 1,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 1,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-001567",
    "anciennete_mois": 8,
    "sieges_souscrits": 21,
    "utilisateurs_actifs": 0,
    "taux_adoption_pct": 0.0,
    "connexions_30j": 0,
    "heures_usage_30j": 0.0,
    "fonctionnalites_utilisees": 0,
    "nb_integrations": 0,
    "derniere_connexion_jours": 33,
    "tickets_support_90j": 2,
    "delai_reponse_support_h": 5.16,
    "csat": 3,
    "retards_paiement_12m": 1,
    "revenu_mensuel_recurrent_eur": 768.78,
    "inactivite_relative": 0.17,
    "inactif_30j": 1,
    "taux_fonctionnalites": 0.0,
    "polarite_csm_alerte": 1,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 1,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-003309",
    "anciennete_mois": 28,
    "sieges_souscrits": 60,
    "utilisateurs_actifs": 13,
    "taux_adoption_pct": 19.25,
    "connexions_30j": 1,
    "heures_usage_30j": 0.28,
    "fonctionnalites_utilisees": 4,
    "nb_integrations": 2,
    "derniere_connexion_jours": 23,
    "tickets_support_90j": 2,
    "delai_reponse_support_h": 11.6,
    "csat": 2,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 1395.01,
    "inactivite_relative": 0.02,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.23,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 1
  },
  {
    "client_id": "CLI-000421",
    "anciennete_mois": 11,
    "sieges_souscrits": 7,
    "utilisateurs_actifs": 6,
    "taux_adoption_pct": 82.21,
    "connexions_30j": 52,
    "heures_usage_30j": 31.15,
    "fonctionnalites_utilisees": 4,
    "nb_integrations": 3,
    "derniere_connexion_jours": 0,
    "tickets_support_90j": 2,
    "delai_reponse_support_h": 16.04,
    "csat": 4,
    "retards_paiement_12m": 1,
    "revenu_mensuel_recurrent_eur": 98.41,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.53,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 1,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-001758",
    "anciennete_mois": 12,
    "sieges_souscrits": 46,
    "utilisateurs_actifs": 7,
    "taux_adoption_pct": 13.65,
    "connexions_30j": 1,
    "heures_usage_30j": 0.11,
    "fonctionnalites_utilisees": 3,
    "nb_integrations": 1,
    "derniere_connexion_jours": 17,
    "tickets_support_90j": 5,
    "delai_reponse_support_h": 10.64,
    "csat": 2,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 2143.16,
    "inactivite_relative": 0.06,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.12,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 0,
    "niveau_anciennete_etabli": 1,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-004786",
    "anciennete_mois": 1,
    "sieges_souscrits": 32,
    "utilisateurs_actifs": 16,
    "taux_adoption_pct": 49.65,
    "connexions_30j": 29,
    "heures_usage_30j": 9.84,
    "fonctionnalites_utilisees": 7,
    "nb_integrations": 0,
    "derniere_connexion_jours": 0,
    "tickets_support_90j": 3,
    "delai_reponse_support_h": 11.32,
    "csat": 3,
    "retards_paiement_12m": 1,
    "revenu_mensuel_recurrent_eur": 617.97,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.45,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-002037",
    "anciennete_mois": 1,
    "sieges_souscrits": 138,
    "utilisateurs_actifs": 108,
    "taux_adoption_pct": 91.94,
    "connexions_30j": 45,
    "heures_usage_30j": 13.17,
    "fonctionnalites_utilisees": 12,
    "nb_integrations": 0,
    "derniere_connexion_jours": 0,
    "tickets_support_90j": 0,
    "delai_reponse_support_h": 2.1,
    "csat": 5,
    "retards_paiement_12m": 1,
    "revenu_mensuel_recurrent_eur": 6355.68,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.43,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-001672",
    "anciennete_mois": 2,
    "sieges_souscrits": 110,
    "utilisateurs_actifs": 20,
    "taux_adoption_pct": 21.26,
    "connexions_30j": 1,
    "heures_usage_30j": 0.3,
    "fonctionnalites_utilisees": 2,
    "nb_integrations": 0,
    "derniere_connexion_jours": 8,
    "tickets_support_90j": 2,
    "delai_reponse_support_h": 5.34,
    "csat": 4,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 4974.96,
    "inactivite_relative": 0.14,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.08,
    "polarite_csm_alerte": 1,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-004452",
    "anciennete_mois": 1,
    "sieges_souscrits": 17,
    "utilisateurs_actifs": 12,
    "taux_adoption_pct": 67.86,
    "connexions_30j": 46,
    "heures_usage_30j": 38.45,
    "fonctionnalites_utilisees": 6,
    "nb_integrations": 0,
    "derniere_connexion_jours": 0,
    "tickets_support_90j": 0,
    "delai_reponse_support_h": 12.93,
    "csat": 5,
    "retards_paiement_12m": 3,
    "revenu_mensuel_recurrent_eur": 428.49,
    "inactivite_relative": 0.0,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.36,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-001002",
    "anciennete_mois": 1,
    "sieges_souscrits": 67,
    "utilisateurs_actifs": 44,
    "taux_adoption_pct": 61.35,
    "connexions_30j": 26,
    "heures_usage_30j": 22.29,
    "fonctionnalites_utilisees": 4,
    "nb_integrations": 0,
    "derniere_connexion_jours": 1,
    "tickets_support_90j": 0,
    "delai_reponse_support_h": 12.92,
    "csat": 5,
    "retards_paiement_12m": 0,
    "revenu_mensuel_recurrent_eur": 707.92,
    "inactivite_relative": 0.03,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.57,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 0,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 1,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  },
  {
    "client_id": "CLI-003056",
    "anciennete_mois": 1,
    "sieges_souscrits": 50,
    "utilisateurs_actifs": 14,
    "taux_adoption_pct": 36.92,
    "connexions_30j": 13,
    "heures_usage_30j": 2.99,
    "fonctionnalites_utilisees": 6,
    "nb_integrations": 0,
    "derniere_connexion_jours": 1,
    "tickets_support_90j": 4,
    "delai_reponse_support_h": 15.76,
    "csat": 3,
    "retards_paiement_12m": 1,
    "revenu_mensuel_recurrent_eur": 1076.0,
    "inactivite_relative": 0.03,
    "inactif_30j": 0,
    "taux_fonctionnalites": 0.27,
    "polarite_csm_alerte": 0,
    "polarite_csm_neutre": 1,
    "polarite_csm_positif": 0,
    "polarite_csm_absent": 0,
    "niveau_anciennete_recent": 1,
    "niveau_anciennete_etabli": 0,
    "niveau_anciennete_ancien": 0
  }
];
